<template>
    <img
        src="/logo_web.webp"
        alt="GrowithBI"
        width="540"
        height="131"
        class="object-contain"
        loading="lazy"
        decoding="async"
    />
</template>
